Modified Deploy workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,7 +36,10 @@ jobs:
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_KEY }}
         script: |
+          set -e  # Stop execution if any command fails
           sudo docker pull amithrao/vaultpay_user:latest
-          sudo docker stop vaultpay-container || true
-          sudo docker rm vaultpay-container || true
+          if sudo docker ps -q -f name=vaultpay-container; then
+            sudo docker stop vaultpay-container
+            sudo docker rm vaultpay-container
+          fi
           sudo docker run -d --name vaultpay-container -p 3005:3000 amithrao/vaultpay_user:latest
